line-length = 88
indent-width = 4

target-version = "py312"

[lint]
select = ["ALL"]

# COM812: Trailing Comma (Only covers single line trailing commas, seems out of place)
# D: Doc style
# EM: Error messages
# FBT: Boolean Trap (Slower)
# N802: Function name should be lowercase
# PTH: Use Pathlib (Wants slower API used)
# SLF001: Private member access
# TRY003: Avoid specifying long messages outside the exception class (Slower and less clear)
ignore = ["COM812", "D", "EM", "FBT", "N802", "PTH", "SLF001", "TRY003"]

[lint.extend-per-file-ignores]

# ANN201: Missing return type
# PT011: Pytest raises
"tests/*" = ["ANN201", "PT011", "S101"]

[lint.isort]
known-third-party = ["nuitka"]

[format]
quote-style = "double"
indent-style = "space"
