line-length = 88
indent-width = 4

target-version = "py312"

[lint]
extend-select = ["C4", "E", "FURB", "F", "I", "PERF", "PL", "Q", "RET", "SIM", "UP", "W", "YTT"]

[lint.isort]
known-third-party = ["nuitka"]

[format]
quote-style = "double"
indent-style = "space"
