[project]
authors         = [
    {name = "James Demetris"},
]
name            = "personal-python-ast-optimizer"
readme          = "README.md"
requires-python = ">=3.11"
dynamic         = ["dependencies", "version"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}
version         = {file = "version.txt"}
